// Renders a real Claude-generated diagnostic (lib/consult/prompt.ts's
// DiagnosticResult) into a short, downloadable, on-brand PDF report — the
// actual "quick diagnostic / roadmap" deliverable prospects expect from the
// Guided Intake tab. Embeds the site's real brand fonts (Rubik, Black Han
// Sans) so the report reads as authentically PRIONATION.io, not a generic
// pdfkit default.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import PDFDocument from "pdfkit";
import { CONTACT_EMAIL, OFFERS, SITE_URL, SITE_NAME, TEAM } from "@/lib/seo/site";
import type { DiagnosticResult, ConsultLocale } from "@/lib/consult/prompt";

const ACCENT = "#5865f2";
const ACCENT_DARK = "#3843b0";
const ACCENT_TINT = "#eef0fe";
const INK = "#101014";
const SOFT = "#3f424a";
const MUTED = "#7a7d85";
const LINE = "#e3e5ec";

// Pre-converted copies of the site's real brand fonts (app/[locale]/layout.tsx
// loads the same families as woff2). pdfkit can't embed woff2 directly, and
// decoding it at runtime (wawoff2, an Emscripten/WASM build) turned out to be
// unreliable once bundled ("Unknown font format" — the WASM binding didn't
// survive Turbopack, even marked external) — so these .ttf files are
// converted once and committed instead of decoded on every request. To
// regenerate after a brand font update, decode the new woff2 with wawoff2
// (`npx --package wawoff2 -e "require('wawoff2').decompress(...)"`) and
// overwrite the files below.
const FONT_FILES = {
  rubik: "lib/consult/fonts/rubik-regular.ttf",
  rubikBold: "lib/consult/fonts/rubik-bold.ttf",
  blackHanSans: "lib/consult/fonts/black-han-sans.ttf",
} as const;

let fonts: Record<keyof typeof FONT_FILES, Buffer> | null = null;

function loadFonts() {
  if (!fonts) {
    fonts = Object.fromEntries(
      Object.entries(FONT_FILES).map(([key, relPath]) => [
        key,
        // turbopackIgnore: these exact files are force-included via
        // next.config.ts's outputFileTracingIncludes — without this,
        // Turbopack's tracer treats process.cwd() + a variable as
        // untraceable and (per its own build warning) falls back to
        // tracing the whole project.
        readFileSync(join(/* turbopackIgnore: true */ process.cwd(), relPath)),
      ]),
    ) as Record<keyof typeof FONT_FILES, Buffer>;
  }
  return fonts;
}

type PdfLabels = {
  kicker: string;
  bottleneck: string;
  path: string;
  roadmap: string;
  roi: string;
  ctaTitle: string;
  ctaBody: (offerName: string, range: string, duration: string) => string;
  ctaLine: string;
  emailLabel: string;
  websiteLabel: string;
  teamLabel: string;
  disclaimer: string;
};

const LABELS: Record<ConsultLocale, PdfLabels> = {
  en: {
    kicker: "AI Quick Diagnostic",
    bottleneck: "Bottleneck",
    path: "Recommended path",
    roadmap: "Roadmap",
    roi: "Estimated impact",
    ctaTitle: "Ready to go deeper?",
    ctaBody: (offerName: string, range: string, duration: string) =>
      `Start with the ${offerName} (${range}, ${duration}) and your conversation carries straight into the scoping call — no repeating yourself.`,
    ctaLine: "Book your",
    emailLabel: "Email",
    websiteLabel: "Website",
    teamLabel: "Team",
    disclaimer:
      "This report was generated by an AI assistant from a short self-reported form. Figures are estimates, not a quote.",
  },
  fr: {
    kicker: "Diagnostic IA rapide",
    bottleneck: "Goulot d'étranglement",
    path: "Parcours recommandé",
    roadmap: "Feuille de route",
    roi: "Impact estimé",
    ctaTitle: "Prêt à aller plus loin ?",
    ctaBody: (offerName: string, range: string, duration: string) =>
      `Démarrez avec ${offerName} (${range}, ${duration}) — votre échange est directement transmis à l'appel de cadrage, sans rien répéter.`,
    ctaLine: "Réservez votre",
    emailLabel: "E-mail",
    websiteLabel: "Site web",
    teamLabel: "Équipe",
    disclaimer:
      "Ce rapport a été généré par un assistant IA à partir d'un court formulaire auto-déclaré. Les chiffres sont des estimations, pas un devis.",
  },
  id: {
    kicker: "Diagnostik Cepat AI",
    bottleneck: "Hambatan",
    path: "Jalur yang disarankan",
    roadmap: "Peta jalan",
    roi: "Perkiraan dampak",
    ctaTitle: "Siap melangkah lebih jauh?",
    ctaBody: (offerName: string, range: string, duration: string) =>
      `Mulai dengan ${offerName} (${range}, ${duration}) — percakapan Anda langsung terhubung ke sesi scoping, tanpa perlu mengulang.`,
    ctaLine: "Pesan",
    emailLabel: "Email",
    websiteLabel: "Situs web",
    teamLabel: "Tim",
    disclaimer:
      "Laporan ini dibuat oleh asisten AI dari formulir singkat yang diisi sendiri. Angka adalah estimasi, bukan penawaran resmi.",
  },
};

function offerRange(offer: (typeof OFFERS)[number]): string {
  return "maxPrice" in offer && offer.maxPrice
    ? `EUR ${offer.minPrice}-${offer.maxPrice}`
    : `EUR ${offer.price}`;
}

function offerDuration(offerName: string): string {
  // Durations aren't a separate OFFERS field — pull the well-known ones out
  // of each offer's published description rather than hardcode a parallel list.
  const offer = OFFERS.find((o) => o.name === offerName);
  const match = offer?.description.match(/(\d+[-–]?\d*\s*(?:week|month)s?)/i);
  return match ? match[1] : "";
}

export function buildDiagnosticPdf(
  data: DiagnosticResult,
  locale: ConsultLocale,
): Promise<Buffer> {
  const L = LABELS[locale] ?? LABELS.en;
  const fonts = loadFonts();

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 0 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.registerFont("Rubik", fonts.rubik);
    doc.registerFont("Rubik-Bold", fonts.rubikBold);
    doc.registerFont("BlackHanSans", fonts.blackHanSans);

    const pageW = doc.page.width;
    const marginX = 56;
    const contentW = pageW - marginX * 2;

    // ── Header band ──
    doc.rect(0, 0, pageW, 108).fill(ACCENT);
    doc
      .fillColor("#ffffff")
      .font("BlackHanSans")
      .fontSize(27)
      .text(SITE_NAME, marginX, 26, { characterSpacing: 0.3 });
    doc
      .font("Rubik-Bold")
      .fontSize(10.5)
      .fillColor("#ffffff")
      .text(L.kicker.toUpperCase(), marginX, 66, { characterSpacing: 0.6 });

    doc.y = 140;
    doc.x = marginX;

    const section = (title: string) => {
      doc.moveDown(0.7);
      doc
        .font("Rubik-Bold")
        .fontSize(9)
        .fillColor(ACCENT)
        .text(title.toUpperCase(), marginX, doc.y, { width: contentW, characterSpacing: 0.5 });
      doc.moveDown(0.25);
    };

    section(L.bottleneck);
    doc.font("Rubik").fontSize(11).fillColor(SOFT).text(data.bottleneckSummary, { width: contentW, lineGap: 2 });

    section(L.path);
    doc
      .font("Rubik-Bold")
      .fontSize(11.5)
      .fillColor(ACCENT_DARK)
      .text(data.recommendedOffer, { width: contentW, continued: true })
      .font("Rubik")
      .fontSize(11)
      .fillColor(SOFT)
      .text(`  —  ${data.pathSummary}`, { width: contentW, lineGap: 2 });

    section(L.roadmap);
    data.roadmapSteps.forEach((step, i) => {
      doc
        .font("Rubik-Bold")
        .fontSize(11)
        .fillColor(INK)
        .text(`${i + 1}. ${step.title}`, marginX, doc.y, { width: contentW, continued: true })
        .font("Rubik")
        .fontSize(10)
        .fillColor(MUTED)
        .text(`   ${step.timeframe}`, { width: contentW });
      doc
        .font("Rubik")
        .fontSize(10.5)
        .fillColor(SOFT)
        .text(step.description, marginX + 14, doc.y, { width: contentW - 14, lineGap: 1 });
      doc.moveDown(0.4);
    });

    section(L.roi);
    doc.font("Rubik").fontSize(11).fillColor(SOFT).text(data.roiEstimateLabel, { width: contentW, lineGap: 2 });

    // ── CTA box ──
    doc.moveDown(1);
    const ctaOffer = OFFERS.find((o) => o.name === data.recommendedOffer) ?? OFFERS[0];
    const ctaTop = doc.y;
    const ctaPad = 18;
    // Measure the body copy height first so the tinted box fits it exactly.
    const ctaBodyText = L.ctaBody(ctaOffer.name, offerRange(ctaOffer), offerDuration(ctaOffer.name));
    doc.font("Rubik").fontSize(10.5);
    const ctaBodyHeight = doc.heightOfString(ctaBodyText, { width: contentW - ctaPad * 2 });
    const ctaBoxHeight = ctaPad * 2 + 22 + ctaBodyHeight + 8 + 16;

    doc.roundedRect(marginX, ctaTop, contentW, ctaBoxHeight, 10).fill(ACCENT_TINT);
    doc
      .font("Rubik-Bold")
      .fontSize(13)
      .fillColor(ACCENT_DARK)
      .text(L.ctaTitle, marginX + ctaPad, ctaTop + ctaPad, { width: contentW - ctaPad * 2 });
    doc
      .font("Rubik")
      .fontSize(10.5)
      .fillColor(SOFT)
      .text(ctaBodyText, marginX + ctaPad, doc.y + 4, { width: contentW - ctaPad * 2, lineGap: 1 });
    doc
      .font("Rubik-Bold")
      .fontSize(11)
      .fillColor(ACCENT)
      .text(`${L.ctaLine} ${ctaOffer.name} → `, marginX + ctaPad, doc.y + 8, { continued: true })
      .text(CONTACT_EMAIL, { link: `mailto:${CONTACT_EMAIL}`, underline: true });

    doc.y = ctaTop + ctaBoxHeight + 22;

    // ── Footer / contact block ──
    doc.x = marginX;
    doc.moveTo(marginX, doc.y).lineTo(pageW - marginX, doc.y).lineWidth(0.5).strokeColor(LINE).stroke();
    doc.moveDown(0.6);
    doc
      .font("Rubik-Bold")
      .fontSize(8.5)
      .fillColor(MUTED)
      .text(`${L.teamLabel.toUpperCase()}`, marginX, doc.y, { characterSpacing: 0.4, continued: true })
      .font("Rubik")
      .fillColor(SOFT)
      .text(`  ${TEAM.map((p) => `${p.name} — ${p.jobTitle}`).join("  ·  ")}`);
    doc.moveDown(0.35);
    doc
      .font("Rubik-Bold")
      .fontSize(8.5)
      .fillColor(MUTED)
      .text(`${L.emailLabel.toUpperCase()}`, marginX, doc.y, { characterSpacing: 0.4, continued: true })
      .font("Rubik")
      .fillColor(ACCENT)
      .text(`  ${CONTACT_EMAIL}`, { link: `mailto:${CONTACT_EMAIL}`, underline: true, continued: true })
      .font("Rubik-Bold")
      .fillColor(MUTED)
      .text(`    ${L.websiteLabel.toUpperCase()}`, { characterSpacing: 0.4, continued: true })
      .font("Rubik")
      .fillColor(ACCENT)
      .text(`  ${SITE_URL.replace(/^https?:\/\//, "")}`, { link: SITE_URL, underline: true });
    doc.moveDown(0.6);
    doc.font("Rubik").fontSize(8).fillColor(MUTED).text(L.disclaimer, marginX, doc.y, { width: contentW, lineGap: 1 });

    doc.end();
  });
}
